In [166]:
from fileinput import filename

import numpy as np
import numpy.linalg as la

#Matrices

### Simple matrix

In [167]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Matrix shape is a tuple storing the number of size of each dimentions.
For 2D matrices, the order is always rows-columns.

In [168]:
m.shape

(2, 3)

In [169]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
type(m)

numpy.ndarray

In [171]:
n = np.array([
    [[1,2],[3,4]],
    [[1,2],[3,4]]
])
n.shape

(2, 2, 2)

### Special matrices

#### Identity

In [172]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
#### Zeros

In [174]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Ones

In [175]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Indexing

For two dimentional matrices, rows are dimention 0 and columns are dimention 1.

In [176]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [177]:
m[1, 2]

np.int64(6)

##Slicing

Use the : symbol to get all values across a dimention.

In [178]:
m[1, :]

array([4, 5, 6])

The : can also represent a range

In [179]:
m[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Reshaping


Preserve the data, but change the shape of the matrix.

In [180]:
m = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
m.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

Reshape a matrix into a single row, figuring out the correct number of columns


In [181]:
m.reshape((1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [182]:
f = m.reshape(-1)
f

array([1, 2, 3, 4, 5, 6])

In [183]:
f.shape

(6,)

## Getting useful statistics

Specify dimension using the axis keyword.

Minimum and maximum values

In [184]:
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [185]:
m.max(axis=1)

array([2, 4, 6])

<b>Mean, standard deviation, and variance</b>

In [186]:
m.mean(axis=0)

array([3., 4.])

In [187]:
m.std(axis=0)

array([1.63299316, 1.63299316])

In [188]:
m.var(axis=0)

array([2.66666667, 2.66666667])

## Operations on matrices

#### Element-wise

In [189]:
a = np.array([
    [1, 2],
    [3, 4]
])

a + a

array([[2, 4],
       [6, 8]])

In [190]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [191]:
a ** a

array([[  1,   4],
       [ 27, 256]])

#### Matrix multiplication

In [192]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [193]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [1, 1, 1], 
    [1, 1, 1]
])
a.dot(b)

array([[3, 3, 3],
       [7, 7, 7]])

##Common linear algebra operations



In [194]:
import numpy.linalg as la

### Transpose

In [195]:
m = np.array([
    [1, 2],
    [3, 4]
])
m.T

array([[1, 3],
       [2, 4]])

### Eigenvalues and eigenvectors

In [196]:
evals, evects = la.eig(m)

In [197]:
evals

array([-0.37228132,  5.37228132])

In [198]:
evects

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [199]:
m.dot(evects[:,0])

array([ 0.30697009, -0.21062466])

In [200]:
evals[0] * evects[:,0]

array([ 0.30697009, -0.21062466])

### Singular value decomposition

In [201]:
U, s, V = np.linalg.svd(m) 

### Other useful operations
* Determinant: `la.det(m)`
* Norm: `la.norm(m)`
* Inverse: `la.inv(m)`

# Vectors

A vector is a special case of a matrix, and has a single dimension.

In [202]:
np.array([0.1, 0.3, 0.1, 0.5])

array([0.1, 0.3, 0.1, 0.5])

Comma after length unpacks the first and only element of the tuple into the variable

In [203]:
p = np.array([0.1, 0.3, 0.1, 0.5])
length, = p.shape
length

4

## Filtering

In [204]:
p > 0.4

array([False, False, False,  True])

In [205]:
p[p > 0.4]

array([0.5])

## Searching and sorting


In [206]:
p.min()

np.float64(0.1)

In [207]:
p.max()

np.float64(0.5)

Index of the max value in the array

In [208]:
p.argmax()

np.int64(3)

Sorting the values

In [209]:
p.sort()
p

array([0.1, 0.1, 0.3, 0.5])

Getting the indeces that correspond to a sorted order of the elements

In [210]:
p = np.array([0.1, 0.3, 0.1, 0.5])
p.argsort()

array([0, 2, 1, 3])

In [211]:
events = np.array(['A', 'B', 'C', 'D'])

Suppose we have an array of events, and `p` defines the probability mass function for these event.

To get the two most likely events, we need to figure out the indices of the top two values.

Note: the fancy indexing `[::-1]` reverses the elements in the array using Python slice syntax (start : stop : step).

In [212]:
i = p.argsort()[::-1]
i

array([3, 1, 2, 0])

Getting the top most probable event is easy now:

In [213]:
events[i[:2]]

array(['D', 'B'], dtype='<U1')

# Working with data


###Loading data from a text file

Specify the delimiter: comma, tab, space, etc.

In [214]:
path = 'sample_text'
# Create a text file
with open(path, 'w') as f:
    f.write('1, 2, 3')
np.genfromtxt(path, delimiter=',')

array([1., 2., 3.])

`genfromtxt` has a lot of useful optional ([arguments](http://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) )

Allows to specify the datatype to load the data as, specify comment format, skipping headers, etc.

### Loading data from a Matlab file with scipy


In [215]:
from scipy.io import loadmat
data = {}
loadmat(filename, data)

TypeError: expected str, bytes or os.PathLike object, not function

`data` is a now dictionary of variable name to data. If the Matlab dump contained a variable `D`, access it by `data['D']` 

### Dumping numpy data to file

In [160]:
data = np.array([1, 2, 3])
np.save('numpy_data', data)

### Loading numpy data from file

In [161]:
data = np.load('numpy_data.npy')
data

array([1, 2, 3])

In [165]:
m2 = np.arange(9).reshape((3, 3))
m2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])